[On going] Change apartment page header
cornell-dti/cu-apts pull request #165
Opened 2022-03-21 01:47 UTC by thuypham03

This PR means to change the apartment page header by:
- Adding address of the apartment (if different from the apartment's name) below its name
- Move number of reviews and heart rating section to under the apartment's photo

Progress [done]:
- Move number of reviews and heart rating section to under the apartment's photo

2022-03-21 01:48 UTC, thuypham03 commented
issue #153

2022-03-31 19:47 UTC, samliu10 requested changes
Looks good except make sure the reviews and hearts are on the same line. See designs
<img width="291" alt="Screen Shot 2022-03-31 at 3 45 57 PM" src="https://user-images.githubusercontent.com/57203639/161136965-4842b3cf-386e-4556-9a3a-961947379bbd.png">

2022-04-17 21:35 UTC, thuypham03 commented
@samliu10  for this commit, I try to put the review and heart rate on the same line, but I cannot find way to also put the buttons on the same line as well, can you help me take a look of it, the code of this part is in frontend/src/pages/ApartmentPage.tsx (line 197-273)

2022-04-18 05:14 UTC, samliu10 commented
I actually think this is a question for @shelost because there is not enough room for everything to be on one line— could you make a design for what this should look like at different breakpoints? One idea is to have the review information + "leave a review" button be on the same line at opposite ends, and then move the review sorting to the second line.

2022-04-22 01:53 UTC, samliu10 approved these changes

2022-04-22 01:53 UTC, samliu10 commented on frontend/src/pages/ApartmentPage.tsx
> +      <Grid container alignItems="center">
Based on new designs, I changed it to look like this
<img width="835" alt="Screen Shot 2022-04-21 at 8 55 58 PM" src="https://user-images.githubusercontent.com/57203639/164580892-afd11d58-8475-4a65-b867-ae7592f76ccf.png">

Here's a video showing resizing: 

https://user-images.githubusercontent.com/57203639/164580926-953cf0cf-6844-47e7-bced-1c91dec9a2ad.mov

2022-04-22 01:53 UTC, samliu10 commented on frontend/src/components/Review/Review.tsx
> -                  <Grid item>
Removed because there are no reviews from Ithaca Tenant Union

2022-04-24 17:57 UTC, merged