Landlord card
cornell-dti/cu-apts pull request #175
Opened 2022-04-30 02:40 UTC by jiayuangu762943

Summary 

This pull request is the first step towards populating the search results page. It shows landlord cards in a row.

 
![Screen Shot 2022-04-29 at 10 33 14 PM](https://user-images.githubusercontent.com/100146921/166087250-0db24201-a0d9-4f45-8bd4-6f9fc078037e.png)

![Screen Shot 2022-04-29 at 10 33 01 PM](https://user-images.githubusercontent.com/100146921/166087252-10384fbf-f1b5-4a7f-8eb9-7fe947d1d44a.png)

Test Plan 

- At most three landlord cards is shown for a search query 
- could have none or one related landlord cards

2022-04-30 15:11 UTC, samliu10 requested changes
Nice job! On figma, I see this as the mobile version: 
<img width="328" alt="Screen Shot 2022-04-30 at 11 09 20 AM" src="https://user-images.githubusercontent.com/57203639/166111183-4e9488b0-cc5b-42dc-b8fc-72096de5339d.png">


I'm wondering if we should have each card take up the full width instead of putting all three next to each other. Otherwise, the font size will need to shrink since right now the landlord names overflow and get cut off. There may need to be some frontend fixes based on what Heewon says about the designs and how the components should resize when the screen size changes, e.g. define more breakpoints, deal with the size of the image, etc. Let's get some clarification on that!

2022-04-30 15:11 UTC, samliu10 commented on frontend/src/components/LandlordCard/LandlordCard.tsx
> +  const classes = useStyles();
You can actually destructure this so that you don't have to keep using `classes.`! 
```
const {card, marginTxt, ... } = useStyles();
```

2022-04-30 15:11 UTC, samliu10 commented on frontend/src/components/LandlordCard/LandlordCard.tsx
> +  const matches = useMediaQuery('(min-width:960px)');
Maybe we should ask @shelost about this — should the image disappear on mobile?

2022-05-05 20:35 UTC, samliu10 approved these changes
LGTM

2022-05-05 20:43 UTC, merged

2022-05-05 21:14 UTC, huyl3 commented
Congrats 🎉