[WIP] Removing Landlords and Adding Apt Cards on the Search Page (2/2)
cornell-dti/cu-apts pull request #191
Opened 2022-10-08 01:10 UTC by juliejeong

This PR is part 2 of 2 addressing Issue #184 with PR #190.

[WORK IN PROGRESS]
The finished PR should look like this:
![image](https://user-images.githubusercontent.com/75141596/194680122-66799ba5-3579-4d9e-ab15-5f4d81a8a9b0.png)

2022-10-08 01:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cornell-dti/cu-apts?pullRequest=191) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cornell-dti/cu-apts?pullRequest=191) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: juliejeong<br/>:x: juliejeongc<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cornell-dti/cu-apts?pullRequest=191) it.</sub>

2022-10-11 20:12 UTC, jiayuangu762943 commented
Great progress! Just two things. First remember to clear the unused imports and variables as for the last PR. Second don't commit package.json and yarn.lock as it will affect the dependencies globally

2022-10-28 16:58 UTC, cyrus14 requested changes
Hi Julie! This PR is going to be an integral feature in CUApts so I'm super excited for this to eventually be merged. After looking through the file changes, I saw that you added 1885 lines and removed 1865 lines. Just to reiterate what Jiayuan mentioned, you should remove yarn.lock and package.json from the commit because these are sources that don't need changing for this feature. Lastly, there were multiple instances of unused imports and variables so removing those would help complete this commit. Again, great work and I'm super excited for this to be merged after these changes!

2022-10-28 19:15 UTC, closed without merging

2022-10-28 19:16 UTC, juliejeong commented
CLOSING THIS PR DUE TO CHANGES IN IMPLEMENTATION PLANS