Corrected the number of approved reviews on the Home page
cornell-dti/cu-apts pull request #248
Opened 2023-03-19 19:05 UTC by jesshan700

### Summary 
Corrected the number of approved reviews shown on the home page. Looked through backend code to get a better understanding of the app infrastructure. 

This pull request is the first step towards fixing the number of approved reviews on the home page. 

- [X] Fixed the number of approved reviews so that it shows the correct number of approved reviews on the home page.

### Test Plan 

Added a new review and manually changed the status from PENDING -> APPROVED to see if the number of approved requests were correct. 

### Notes 

### Breaking Changes  

- Database schema change (anything that changes Firestore collection structure)
- Other change that could cause problems (Detailed in notes)

2023-03-19 19:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cornell-dti/cu-apts?pullRequest=248) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cornell-dti/cu-apts?pullRequest=248) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cornell-dti/cu-apts?pullRequest=248) it.</sub>

2023-03-19 19:27 UTC, thuypham03 requested changes

2023-03-19 19:27 UTC, thuypham03 commented on backend/src/app.ts
> -app.put('/update-review-status/:reviewDocId/:newStatus', async (req, res) => {
Can you revert the deletion of this API, we will need this at other task!

2023-03-21 16:24 UTC, thuypham03 approved these changes
Great job! I have tested it out and it works perfectly. Hope that this bug helps you understand better about CUApts codebase.

2023-03-21 16:29 UTC, merged

2023-03-27 01:25 UTC, ggsawatyanon commented
Already merged, but the backend logic looks great. This works as intended in testing.