Implemented Profile Button Dropdown
cornell-dti/cu-apts pull request #315
Opened 2023-11-06 21:27 UTC by ggsawatyanon

### Summary 

This pull request is the first step towards implementing the profile button dropdown as seen in Katherine's figma.

- [x] implemented profile button dropdown
- [x] created new saved apartments page
- [x] implemented bear profile image for safety if user is null

### Test Plan 

<img width="1512" alt="image" src="https://github.com/cornell-dti/cu-apts/assets/125820523/cc3db81a-c942-418f-8cc2-f971a72d8693">

<img width="787" alt="image" src="https://github.com/cornell-dti/cu-apts/assets/125820523/9f51c971-a374-4bde-9aba-71d7e80fbacb">

blank saved apartments page:
<img width="1512" alt="image" src="https://github.com/cornell-dti/cu-apts/assets/125820523/d171c1c2-1aab-48c0-a078-ac0010de8314">

### Notes

2023-11-12 22:41 UTC, AnkitLakkapragada approved these changes
Awesome changes! I tested it and there don't seem to be any bugs. This change is very important and really improves the usability for our users. I also really liked all the specifications that you added. Great work

2023-11-12 22:44 UTC, cyrus14 approved these changes
Hey Grace! This is such an important PR as we are getting closer and closer to replicating what Katherine had designed in her Figma mockup. The saved apartments page is going to be crucial from a user experience standpoint because they can now go back to their favorites. I tested the Profile button dropdown and everything works as intended. It also works when dynamically updated the window. Great job using percentages rather than magic numbers. Overall, outstanding job and cannot wait to see this in production!

2023-11-13 00:22 UTC, jesshan700 commented
Hi Grace! Your code looks really clean and this is a really important feature for our new updates! I really like how seamless the ui is and it will allow the user to look back on saved apartments now as well. Good job on this PR!

2023-11-14 00:13 UTC, thuypham03 requested changes
Please upload new changes regarding mobile stacks.

2023-11-18 22:45 UTC, thuypham03 commented on frontend/src/App.tsx
> +import SavedApartmentsPage from './pages/SavedApartmentsPage';
Please change to `SavedPage` (because we also have saved landlords and saved reviews in this page)

2023-11-18 22:46 UTC, thuypham03 commented on frontend/src/App.tsx
> +              path="/savedapartments/:profileId"
Change the path to `path="/saved"` without `profileId`, we should not expose the id here, all info should be in user state and be retrieved from then.

2023-11-20 00:49 UTC, thuypham03 approved these changes
Amazing job! A brand new drawer has been included that leads to bookmarks and profile page. Nice and clean UI implementation!

2023-11-20 00:51 UTC, merged