[WIP] Delete review endpoint & Edit review endpoint
cornell-dti/cu-apts pull request #320
Opened 2023-11-11 23:15 UTC by cyrus14

### Summary 

- Added edit and delete review endpoints into app.ts which will be used for user profile page actions.

### Test Plan 

Test with Postman

2023-11-13 04:49 UTC, mluo24 reviewed
Nice work Cyrus! I have a few nits, but for the most part it looks great! Great use of the soft delete and validation!

2023-11-13 04:49 UTC, mluo24 commented on backend/src/app.ts
> +app.put('/api/edit-review/:reviewDocId', async (req, res) => {
Generally the convention is you get the id and then you do the action, so I think `:reviewDocId/edit` would be more apt.

Same with line 348

2023-11-13 04:49 UTC, mluo24 commented on backend/src/app.ts
> +      .update({ ...review, date: new Date(review.date), status: 'PENDING' });
Are you leaving the old date or is this updating it with a new date/do you know which one it should be?

2023-11-13 04:49 UTC, mluo24 commented on backend/src/app.ts
> +    res.status(201).send(reviewDocId);
status code 200 for updating

2023-11-14 00:11 UTC, thuypham03 requested changes

2023-11-14 00:11 UTC, thuypham03 commented on backend/src/app.ts
> +app.put(' :reviewDocId/:newStatus', async (req, res) => {
Please revert back to its original

2023-12-01 05:10 UTC, merged