Implement Landlord Redirect Button (Change to Button Style)
cornell-dti/cu-apts pull request #350
Opened 2024-02-22 01:40 UTC by CasperL1218

Implement Landlord Redirect Button (Change to Button Style)

- [x] Change the landlord redirect text on the review from underlined text to a button style

<img width="866" alt="Screenshot 2024-02-21 at 18 12 49" src="https://github.com/cornell-dti/cu-apts/assets/160357661/2f4f9744-358f-4442-941a-1ad963d4fbf2">
*The [Property: ] text is not underlined now

<img width="845" alt="Screenshot 2024-02-21 at 18 12 53" src="https://github.com/cornell-dti/cu-apts/assets/160357661/58f23d37-89fc-4141-ac49-8b908982e106">
*The text/button area becomes darker when the mouse hovers over it. It has a similar style to the [Visit Landlord] button on ApartmentCard.

2024-02-22 03:10 UTC, kea-roy requested changes
Nice work! Works as intended with responsive styling. Tested on various screen sizes and the button looks correct for all sizes. 

But I don't think any of the styling is necessary. If you want to simplify the code a bit, you can try removing your custom stylings on lines 195-200. I tried running the code without the styling and it seems to look the same. Perhaps Material UI takes care of the styling for this component?

2024-02-22 04:11 UTC, CasperL1218 commented
I tried removing the styling, and it works the same way as intended. 

I have removed the styling on lines 195-200.

2024-02-22 17:01 UTC, kea-roy submitted a review, later dismissed

2024-03-03 08:38 UTC, ggsawatyanon requested changes
Good job on your first task! Good implementation of the button. Could you match the landlord button styling further by making the text not capitalized? Also ensure that the font size is the same as the review text font size.
Example below:
<img width="385" alt="image" src="https://github.com/cornell-dti/cu-apts/assets/125820523/2715be04-72b9-4a21-bc21-73c98e793519">

2024-04-17 21:55 UTC, closed without merging