Implemented Google Map (New Version) in Apartment Page
cornell-dti/cu-apts pull request #357
Opened 2024-03-17 19:27 UTC by CasperL1218

### Summary 

This pull request is the first step toward implementing the Google Map & distance from campus information for the Apartment page.  

Google Map:
- [x] implemented Google Map with default centered at the apartment location (latitude, longitude) 
- [x] implemented apartment icon marker fixed at the apartment coordinate 
- [x] allow user interactions (expand, drag and move, zoom in/out)

Location information:
- [x] implemented display of apartment address 
- [x] implemented display of distance (time required) from campus via walking/driving

### Test Plan 

Location section and Google Map
<img width="1440" alt="Screenshot 2024-03-17 at 14 44 03" src="https://github.com/cornell-dti/cu-apts/assets/160357661/d8b0ebcb-0c3c-4cbf-9d82-0ac4a685ca85">
Google Map drag and move
<img width="1440" alt="Screenshot 2024-03-17 at 14 46 01" src="https://github.com/cornell-dti/cu-apts/assets/160357661/a7b53be5-579e-4a83-99bb-d48207f27e3f">
Google Map zoom in
<img width="1440" alt="Screenshot 2024-03-17 at 14 46 21" src="https://github.com/cornell-dti/cu-apts/assets/160357661/a2c01fc4-ec05-4ded-8de4-b101d031a8e3">
Google Map zoom out
<img width="1440" alt="Screenshot 2024-03-17 at 14 46 30" src="https://github.com/cornell-dti/cu-apts/assets/160357661/b6741edd-40ae-4045-b1d0-f512ca70e1d2">
Google map full-screen expansion
<img width="1440" alt="Screenshot 2024-03-17 at 14 46 39" src="https://github.com/cornell-dti/cu-apts/assets/160357661/84b12ff0-76d7-483c-b552-bd16fae7576f">
Google Map drag and move, zoom in/out (full-screen)
<img width="1440" alt="Screenshot 2024-03-17 at 14 46 48" src="https://github.com/cornell-dti/cu-apts/assets/160357661/5b049d3d-472f-4556-8316-246900888f31">

### Notes 

*Note: the time required for walking/driving to campus is currently hardcoded to 0 

### Future Plans 
- Implement markers & titles for important campus landmarks (e.g., Arts Quad, Eng. Quad)
- Implement modal design for map expansion (instead of the current full-screen expansion)

2024-03-17 22:50 UTC, kea-roy requested changes
## PR Review

This is a really nice implementation of the map. The front-end design looks great on large and small screens, adapting correctly to the page layout even for mobile devices. It looks nearly identical to the Figma design, so great work!

Even though the design is really good, I noticed a few things that could be improved.

1. The pin in the Figma design also has a small red ellipse below the pin, but the SVG file you used doesn't include that ellipse. You could consider updating the SVG file used to include the ellipse or check with the designers if the red ellipse is needed.
<img width="172" alt="S" src="https://github.com/cornell-dti/cu-apts/assets/146872846/8c9349b7-5b55-46e2-95db-3b32ae66ed59">


2. Remove console.log command in MapInfo.tsx: This prints the API key to the console. While good for testing, this is unnecessary and it is probably better to omit it from the console for security reasons.
```
[MapInfo.tsx]

40:  console.log(process.env.GOOGLE_MAP_API_KEY);
```

3. Improving the documentation of your code, for instance adding a doc comment for your MapInfo component, just to make the code easier to understand.

```
[MapInfo.tsx]

32: // add documentation here
33: export default function MapInfo({
```

Overall, these are minor changes and you did a great job!

2024-03-20 20:49 UTC, kea-roy approved these changes

2024-09-23 23:28 UTC, CasperL1218 commented
The implementation of the zoom functionality update tackled 2 issues:

1. Implemented zoom in/out buttons for default/small map and map modal
*Note: the design of the zoom buttons requires further confirmation from the designers to confirm button design styles.

2. Resolved firebase import issue similar to this: https://stackoverflow.com/questions/69971326/firebase-node-modules-firebase-app-dist-app-index-has-no-exported-member-us
Resolved by:
- Adding `export default firebase;` to the end of the `firebase.ts` file
- Adding relative import path to import firebase in the frontend component & page files that are referencing `firebase.User`

2024-10-06 11:48 UTC, kea-roy requested changes
## PR Review

Hi Casper, your implementation of the zoom in-out buttons is going great, I've tested the look and the zoom button's responsiveness on different screens and you have made sure it adapts well. Good work on that!

However, I noticed a few responsiveness issues that could still be addressed.
1. Main screen: wrap text issue
<img width="447" alt="Screenshot 2024-10-06 at 7 27 24 AM" src="https://github.com/user-attachments/assets/0e675f5c-46e7-45c1-bfc0-a656adc8a610">

- Although this is pretty minor, certain screen sizes cause the text to wrap around, creating an inconsistent design. Maybe check with the designers on what the design should look like if the text doesn't fit: most likely either abbreviating the text with ellipsis or making all of the text wrap around and slightly indented.

2. Modal responsiveness: Information cut off 
<img width="1060" alt="Screenshot 2024-10-06 at 7 31 43 AM" src="https://github.com/user-attachments/assets/bf943981-b6af-44df-b842-8d70a3587ab7">

- Even though the map itself is very responsive, the dialog containing all the information is not quite there yet. If a scrollable element is not recommended by the designers, consider removing all of the text below the map on smaller screens (check with designers on this for feedback).

3. Zoom in and out icons
<img width="299" alt="Screenshot 2024-10-06 at 7 31 16 AM" src="https://github.com/user-attachments/assets/c6d10549-e7cb-46d8-923c-db9b1c78de0d">

Remember to update the icons with the correct ones when you get the designs from the designers!

Overall, these are small design issues that just require a bit more specification and feedback from the team. The actual functionality is great! So good job on this PR!

2024-10-08 21:52 UTC, closed without merging