Fix report abuse
cornell-dti/cu-apts pull request #380
Opened 2024-11-18 04:14 UTC by CasperL1218

## Summary
This pull request enhanced the Report Abuse feature for reviews. The new Report Abuse feature provides a more comprehensive process for reporting reviews, and allowing admin to monitor reported reviews to take actions.

Main Requirements Completed:
- [x] Added confirmation modal for reporting
- [x] Added success toast for report submission
- [x] Kept reported reviews visible on apartment page
- [x] Admin section exists for handling reported reviews

Backend Changes Completed:
- [x] Added report functionality to endpoints
- [x] Added report fields to review type
     - [x] Include `date`, `reason`, and `userId`
     - [ ] `reason` field will require future frontend process
- [x] Implemented proper status handling
     - [x] Create `REPORTED` review status
     - [x] Implemented new report entry creation
- [x] Added validation for report submissions
     - [x] Relevant authorization and identity check for report functionality (admin, review owner, etc.)

Frontend Changes Completed:
- [x] Report process
     - [x] Added report confirmation modal
     - [x] Added report abuse success toast
- [x] Page display 
     - [x] Modified review fetching to include reported reviews (so users can see both `APPROVED` and `REPORTED` reviews)
     - [x] Updated ApartmentPage, AdminPage, ProfilePage, LandlordPage, and BookmarkPage
- [x] Review owner page (ProfilePage)  
     - [x] Prevent reported review owner to edit reviews
     - [x] Prevent review owner to report their own reviews
     - [x] Added reported reviews section to profile page
- [x] Admin Page
     - [x] Reported review section
     - [x] Review dropdown UI enhancement  

Review Status Flow Fixed:
- [x] PENDING → APPROVED → can be REPORTED
- [x] Can't report PENDING reviews
- [x] Can't report own reviews
- [x] Reported reviews remain visible to all users

Edge Cases Handled:
- [x] Users can't report their own reviews
- [x] Users can't report pending reviews
- [x] Reported reviews stay visible but can't be edited
- [x] Profile page shows all review statuses correctly

## Test Plan
*Reported reviews in profile page
<img width="1439" alt="Screenshot 2024-11-17 at 22 59 17" src="https://github.com/user-attachments/assets/29e2c360-d9b2-4c38-8745-c236f926fa91">

*Only able to report other users' review. REPORTED reviews are still visible.
<img width="654" alt="Screenshot 2024-11-17 at 23 00 48" src="https://github.com/user-attachments/assets/d0ddafdb-f6a9-4ce8-8dad-92d7e1630426">

*Admin page reported review display
<img width="1440" alt="Screenshot 2024-11-17 at 23 01 08" src="https://github.com/user-attachments/assets/452f79f3-98ed-4b01-b80b-2e66378c9aff">

*Admin page review section dropdown menu
<img width="1440" alt="Screenshot 2024-11-17 at 23 01 29" src="https://github.com/user-attachments/assets/2fa87acb-0e85-4671-8506-2bb879038fed">

Test the following flows:
1. Regular user flow:
   - View an approved review
   - Click report abuse button
   - Confirm report in modal
   - See success toast
   - Verify review remains visible

2. Edge cases:
   - Verify can't report own reviews (report button hidden)
   - Verify can't report pending reviews (pending reviews are only available in owner's profile page, where report button is hidden)
   - Verify reported reviews can't be edited
   - Verify reported reviews show up in profile page

## Notes
- Using lazy migration for the reports field in review documents
- Reported reviews remain visible to prevent abuse of the report system
- Only admins can take action on reported reviews

## Breaking Changes
- Database schema change: Added `reports` array field to review documents (lazy migration)

2024-11-20 02:35 UTC, kea-roy requested changes
## PR Review

You implemented the report abuse confirmation modal really well with no flaws, and the toast works correctly as expected. Good work on these parts.

You also adjusted the app.ts really well, I love the security checks and the logic works correctly. 

I like the addition of the collapsing arrows and it really helps improve the user experience! One minor change would be to switch the open and close state direction to match the convention across our site, so just flip the rotate CSS.

This is the current state, but it should be the opposite. 

<img width="556" alt="Screenshot 2024-11-19 at 6 59 08 PM" src="https://github.com/user-attachments/assets/70948052-6a88-42e4-b192-da05231fa43e">

2024-12-03 02:37 UTC, kea-roy approved these changes
Great work making the requested changes!

2024-12-04 03:19 UTC, ggsawatyanon requested changes
Here are a few changes I'd like to request:
1. Change the admin button wording from "Approve" to "Ignore" for clarity
2. The report abuse button should be visible when the user isn't signed in. If they aren't signed in, it should prompt them to sign in. (Same as the helpful review button)
3. Don't send users email of approved reviews when the report has been ignored.

2024-12-07 06:24 UTC, ggsawatyanon approved these changes

2024-12-07 06:24 UTC, merged