Search Suggestion Bars Re-Design
cornell-dti/cu-apts pull request #382
Opened 2024-12-03 01:34 UTC by CasperL1218

### Summary 

This pull request is the implementation of the search suggestion bars re-design, replacing textual labels with icons to offer more intuitive display. 

- [x] Replaced label text with label icons for each menu item
- [x] Added bottom gray border for each menu item
- [x] Reduced the excessive top padding of the menu list

### Test Plan 

<img width="971" alt="Screenshot 2024-12-02 at 20 30 45" src="https://github.com/user-attachments/assets/a252c8f1-4208-4b6d-9f7b-e99882410a7a">
- New menu item design
<img width="943" alt="Screenshot 2024-12-02 at 20 31 02" src="https://github.com/user-attachments/assets/1ea8fd1c-6033-4083-a100-9449ce47285c">
- Menu items with only building name

### Notes 

Some minor design details were made:
- Border radius added to the menu
- Reduce top/bottom padding space
- Font size modification (now 16px/12px)

2024-12-03 02:35 UTC, kea-roy submitted a review, later dismissed
## PR Review
The design matches the figma really well and your logic for checking which icon to use works perfectly.
Some minor suggestions are to
1. remove Clip import (since it is no longer being used in autocomplete)
2. adjust your padding CSS to be a bit more specific (to resolve the extra padding on the right side)
<img width="135" alt="Screenshot 2024-12-02 at 9 31 49 PM" src="https://github.com/user-attachments/assets/cc27736e-3e9f-42e6-9449-f86ce68ce004">

Since these are minor changes, I've made a commit to resolve them. Great work on this PR!

2024-12-04 01:09 UTC, kea-roy submitted a review, later dismissed
Your changes resolved the issue. Good job checking with the designers for input, and great work on the PR.

2024-12-04 02:23 UTC, ggsawatyanon requested changes
The new icons look great. I'm requesting 2 changes: 
1. Please remove the drop shadow from the search suggestion
<img width="838" alt="image" src="https://github.com/user-attachments/assets/5dd22227-4a61-4b57-ab0f-55d8790efc34">

2. Please fix the mobile side search bar suggestions to add ellipsis '...' to the end of the apatment/landlord name so it doesn't overflow onto the next line
<img width="653" alt="image" src="https://github.com/user-attachments/assets/df9f759c-f6b6-4f8f-8d89-e52bd683e62c">

2024-12-07 05:58 UTC, ggsawatyanon approved these changes

2024-12-07 05:59 UTC, merged