Add Detailed Ratings to Review Component
cornell-dti/cu-apts pull request #46
Opened 2021-03-21 18:45 UTC by menaattia

### Summary 

- [x] added a collapsible section to the Review component that displays detailed reviews
- [x]  added "Helpful" and "Report Abuse" buttons
- [x] added the Navbar to the Landlord page in place of the dummy text
- [x] added placeholder image 

### Test Plan 

Run `yarn start` in the root or frontend workspace, and go to `/landlords/:id` with any id. Change the width of the browser to see how the reviews render on different widths.
**Desktop view:** 
<img width="600" alt="Screen Shot 2021-03-21 at 4 30 53 AM" src="https://user-images.githubusercontent.com/31854132/111916711-a5e2fd00-8a52-11eb-97dc-b2025e6c2569.png">
**Mobile view:**
<img width="400" alt="Screen Shot 2021-03-21 at 4 31 52 AM" src="https://user-images.githubusercontent.com/31854132/111916717-ac717480-8a52-11eb-8bd5-ad917663a7d6.png">

### Notes 

- I didn't implement the "[year] Resident" from the design because I believe that could compromise anonymity, but instead moved the date of review to the right of the component
- I couldn't get the horizontal line between the text and the rating to show using Material-UI Grid

2021-03-21 19:03 UTC, Enochen requested changes

2021-03-21 19:03 UTC, Enochen commented on frontend/src/pages/LandlordPage.tsx
> +      maintenence: 1,
maintenance

2021-03-21 20:12 UTC, ptwu reviewed
looks super good! did a quick scan of the code and only found one thing to nitpick about

2021-03-21 20:12 UTC, ptwu commented on frontend/src/components/Review/DetailedRating.tsx
> +  readonly ratings: Ratings;
`Ratings` should also be `readonly`

2021-03-28 18:05 UTC, ptwu submitted a review, later dismissed

2021-03-28 18:51 UTC, ptwu approved these changes

2021-03-28 18:53 UTC, merged