Connect review to apartment cards
cornell-dti/cu-apts pull request #71
Opened 2021-05-16 06:24 UTC by samliu10

### Summary 

This PR is for changing the "Reviews" button in the navbar to now connect to a new reviews page that is populated with cards where each card represents one of the buildings in the db. Each card links to the landlord reviews for the renting company that owns that particular building. 

This PR also includes a lot of code refactoring: the apartment cards are now their own component, and the previous `/homepageData` endpoint was changed to a generic `/page-data/:page` endpoint that supports retrieving data for the three apartment cards on the home page as well as the apartment cards on the reviews page. If `page` is `'home'`, then data for only three buildings is returned. Otherwise, data for all buildings in the db is returned. 

https://user-images.githubusercontent.com/57203639/118387611-5271d300-b5ed-11eb-8f05-68cf17d9544b.mov

### Test Plan 

Run `yarn start` in the root directory to start a local dev server. 
- Click on the "Reviews" button in the navbar to see the reviews page. 
- Click on an apartment card to navigate to the landlord reviews, and click on the "Reviews" button in the navbar to see the reviews page. 

### Notes
This PR is based off of #70 because #70 fixes a major bug in one of the endpoints.

2021-05-23 02:21 UTC, ptwu commented
@samliu10 you can merge the changes from `main` into this PR now

2021-05-23 06:51 UTC, ptwu commented on frontend/src/components/ApartmentCard/ApartmentCards.tsx
> +            <Grid item xs={12} md={4}>
need a unique `key` prop for each `Grid` item

2021-05-23 18:03 UTC, Enochen requested changes

2021-05-23 18:03 UTC, Enochen commented on frontend/src/components/utils/NavBar/index.tsx
> +        <ThemeProvider theme={muiTheme} key={index}>
Do we need to make a ThemeProvider for each Link (instead of just having one)?

2021-05-23 18:03 UTC, Enochen commented on frontend/src/pages/ReviewPage.tsx
> +    get<any>(`/page-data/reviews`, {
`any` is bad

2021-05-23 18:03 UTC, Enochen commented on frontend/src/pages/ReviewPage.tsx
> +  const [buildingData, setBuildingData] = useState<CardData[]>([]);
Might want to rename `buildingData` here to something else because `buildingData` is the name of a property in `CardData`.

2021-05-24 16:19 UTC, Enochen approved these changes

2021-05-24 16:19 UTC, Enochen commented on backend/src/app.ts
> +  const buildingDocs =
Nit: prefer extracting common functionality

ie `const smth = page === 'home' ? buildingsCollection.limit(3) : buildingsCollection`

`const buildingDocs = (await smth.get()).docs`

2021-05-24 18:55 UTC, ptwu approved these changes

2021-05-24 19:29 UTC, merged